### ISSUE TITLE
useMobileOrientation not working

### ISSUE THREAD

**Issue by jeremylin8** [duskload/react-device-detect#170]
1. Bug description
When I tried to use "const { isLandscape } = useMobileOrientation()", I get "TypeError: Object(...) is not a function"

2. Steps to reproduce
import { useMobileOrientation } from 'react-device-detect';
const { isLandscape } = useMobileOrientation();

**Comment by greekjoel** [comment]
I had the same thing, then I updated react-device-detect to the latest version and tried it a bunch of times but it didn't work. A bit later after restarting my computer I tried with the exakt same code (I had ut commented the code out so I just uncommented it) and suddenly it worked. 🤷

**Comment by gmkhussain** [comment]
It's works with version : 2.1.2

```js
//...
import { useMobileOrientation } from 'react-device-detect';

function App() {

        const mobileOrientation = useMobileOrientation();

        console.log( "Check in console ->", mobileOrientation )
//..
```
